### ISSUE TITLE
Software to Control

### ISSUE THREAD

**Issue by malu254** [Shuraxxx/-Balboa-GS523SZ-with-panel-VL801D-DeluxeSerie-#1]
Hello @Shuraxxx, is there already a finished Software which works to Control the Unit? I would like to add this to my Spa to control it via Mqtt.

**Comment by Shuraxxx** [comment]
> Hello @Shuraxxx, is there already a finished Software which works to Control the Unit? I would like to add this to my Spa to control it via Mqtt.

Hello @malu254, yes. Check out the repository

**Comment by malu254** [comment]
@Shuraxxx  thanks for adding the code to this repository, unfortunately it looks like the "Balboa_GS_Interface.cpp" and the Balboa_GS_Interface.h from your repository do not match the .ino file.
I tried to compile it, but got the Error for every Bit from Bit31 to Bit71 in the Mqtt section. 
![image](https://github.com/Shuraxxx/-Balboa-GS523SZ-with-panel-VL801D-DeluxeSerie--MQTT/assets/77109010/ef84d04c-5c70-4324-8fa7-e5f39dc9e25f)

**Comment by helper0815** [comment]
Hello @Shuraxxx,
I would also like to use the project to control my SPA.
> > Hello @Shuraxxx, is there already a finished Software which works to Control the Unit? I would like to add this to my Spa to control it via Mqtt.
> 
> Hello @malu254, yes. Check out the repository

But, I get the same errors as @malu254
Could you please update the other two files(Balboa_GS_Interface.cpp, Balboa_GS_Interface.h )?

Many thanks in advance

**Comment by zarzak12** [comment]
Hello, I have the same error ... impossible to compile this project

**Comment by Shuraxxx** [comment]
Я  исправил, проверте

**Comment by Shuraxxx** [comment]
> @Shuraxxx thanks for adding the code to this repository, unfortunately it looks like the "Balboa_GS_Interface.cpp" and the Balboa_GS_Interface.h from your repository do not match the .ino file. I tried to compile it, but got the Error for every Bit from Bit31 to Bit71 in the Mqtt section. ![image](https://private-user-images.githubusercontent.com/77109010/286290891-ef84d04c-5c70-4324-8fa7-e5f39dc9e25f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQzNjU5NjgsIm5iZiI6MTcwNDM2NTY2OCwicGF0aCI6Ii83NzEwOTAxMC8yODYyOTA4OTEtZWY4NGQwNGMtNWM3MC00MzI0LThmYTctZTVmMzlkYzllMjVmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTA0VDEwNTQyOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWVjOGYzOWY2YjZmYTBjZDM4NDQzMzFmNTIwOTIzMWQ3NTI2ZTYwOTMzNzVlMjkwOWQ3MjQ0ODNkNmQwZDY2MWMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.jJyR_vNWKW08Owvl0yutyFiH7OIWhQN7E8N9t16vG2g)

Я исправил, проверте

**Comment by malu254** [comment]
> > @Shuraxxx thanks for adding the code to this repository, unfortunately it looks like the "Balboa_GS_Interface.cpp" and the Balboa_GS_Interface.h from your repository do not match the .ino file. I tried to compile it, but got the Error for every Bit from Bit31 to Bit71 in the Mqtt section. ![image](https://private-user-images.githubusercontent.com/77109010/286290891-ef84d04c-5c70-4324-8fa7-e5f39dc9e25f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQzNjU5NjgsIm5iZiI6MTcwNDM2NTY2OCwicGF0aCI6Ii83NzEwOTAxMC8yODYyOTA4OTEtZWY4NGQwNGMtNWM3MC00MzI0LThmYTctZTVmMzlkYzllMjVmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTA0VDEwNTQyOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWVjOGYzOWY2YjZmYTBjZDM4NDQzMzFmNTIwOTIzMWQ3NTI2ZTYwOTMzNzVlMjkwOWQ3MjQ0ODNkNmQwZDY2MWMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.jJyR_vNWKW08Owvl0yutyFiH7OIWhQN7E8N9t16vG2g)
> 
> Я исправил, проверте

Now it works, many thanks for adding your code. I found a small Problem with the OTA Handling and added a PR for it

**Comment by duczz** [comment]
@malu254 how to you import the zip file? i get always an error (the main from this fork i can import)
![image](https://github.com/Shuraxxx/-Balboa-GS523SZ-with-panel-VL801D-DeluxeSerie--MQTT/assets/25475385/616e0fa2-4576-474f-be56-854669c77e2c)

**Comment by malu254** [comment]
> @malu254 how to you import the zip file? i get always an error (the main from this fork i can import) ![image](https://private-user-images.githubusercontent.com/25475385/295863797-616e0fa2-4576-474f-be56-854669c77e2c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ5NjYzNjksIm5iZiI6MTcwNDk2NjA2OSwicGF0aCI6Ii8yNTQ3NTM4NS8yOTU4NjM3OTctNjE2ZTBmYTItNDU3Ni00NzRmLWJlNTYtODU0NjY5Yzc3ZTJjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTExVDA5NDEwOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTEzNDNiM2FlOTYwYmIxMzZlN2JhODBjNDYyNjc5N2QxNzk2YWYxYTExN2M4Y2FjY2QzM2E1NWEwNGFkMTIwYzImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.ThVDpB4YE2v-LF92aAQrtJHCj3IJagQySe_OOu31MKs)

@duczz, Iam using the Arduino IDE, therfore i created a project folder and only used this three files to flash on the ESP8266
https://github.com/Shuraxxx/-Balboa-GS523SZ-with-panel-VL801D-DeluxeSerie--MQTT/blob/main/src/Balboa_GS_Interface.cpp
https://github.com/Shuraxxx/-Balboa-GS523SZ-with-panel-VL801D-DeluxeSerie--MQTT/blob/main/src/Balboa_GS_Interface.h
https://github.com/Shuraxxx/-Balboa-GS523SZ-with-panel-VL801D-DeluxeSerie--MQTT/blob/main/Balboa_GS_MQTT/Balboa_GS_MQTT.ino

**Comment by duczz** [comment]
@malu254 i tried this too. 1 folder with all 3 files and i get this error
![image](https://github.com/Shuraxxx/-Balboa-GS523SZ-with-panel-VL801D-DeluxeSerie--MQTT/assets/25475385/9575a1f6-2d93-4ffc-a2c2-9ca912e244ed)

**Comment by malu254** [comment]
Okay, that shouldn’t be, please try to set it in ““ instead of <>

**Comment by duczz** [comment]
yeah thats work, thank you.
Do you use it with homeassistant too?

**Comment by malu254** [comment]
> yeah thats work, thank you. Do you use it with homeassistant too?

Your welcome, no im Using IOBroker

**Comment by duczz** [comment]
which spa do you use? Balboa-GS523SZ or Balboa-GS510SZ i don't know which project i shoud use i have a Balboa-GS510DZ it looks like both are simulary

**Comment by malu254** [comment]
> which spa do you use? Balboa-GS523SZ or Balboa-GS510SZ i don't know which project i shoud use i have a Balboa-GS510DZ it looks like both are simulary

@duczz I think you schould use this version https://github.com/MagnusPer/Balboa-GS510SZ
