### ISSUE TITLE
should this not be gs523dz ?

### ISSUE THREAD

**Issue by micke85** [Shuraxxx/-Balboa-GS523SZ-with-panel-VL801D-DeluxeSerie-#5]
Hi
Should this not be the gs523DZ, as the display is a 801d ?

to my knowledge, the GSxxxSZ and D displays are not compatible

**Comment by Shuraxxx** [comment]
Apparently you don't know well.

> Hi Should this not be the gs523DZ, as the display is a 801d ?
> 
> to my knowledge, the GSxxxSZ and D displays are not compatible

**Comment by micke85** [comment]
I can be totally wrong, but here it says the same.
 http://service.balboa-instruments.com/appnotes/app_notes_vl801d.htm

**Comment by Shuraxxx** [comment]
Fixed, thanks for the tip
